name: Deploy Next.js Static Site to Beget VPS

on:
    push:
        branches:
            - main # Сценарий запускается при пуше в ветку main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            # 1. Скачиваем код из репозитория
            -   name: Checkout repository
                uses: actions/checkout@v4

            # 2. Устанавливаем Node.js окружение
            -   name: Set up Node.js
                uses: actions/setup-node@v4
                with:
                    node-version: 20
                    cache: 'npm'

            # 3. Устанавливаем зависимости и собираем статику Next.js
            -   name: Install dependencies & Build static site
                run: |
                    npm ci
                    npm run build

            # 4. Переименовываем папку out в public_html (как настроено в Nginx)
            -   name: Prepare folder structure
                run: mv out public_html

            # 5. Надежная отправка файлов на VPS через SFTP
            -   name: Deploy to Beget VPS via SSH
                uses: easingthemes/ssh-deploy@main
                with:
                    SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
                    ARGS: "-rlgoDzc --delete" # Синхронизация файлов с удалением старых
                    REMOTE_HOST: ${{ secrets.HOST }}
                    REMOTE_USER: ${{ secrets.USERNAME }}
                    SOURCE: "public_html/" # Какую локальную папку отправляем
                    TARGET: "/var/www/kk/public_html/" # В какую папку на сервере складываем
